services:
  - type: web
    name: shop-ban-acc-garena
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: shop-db
          property: connectionString
      - key: FLASK_ENV
        value: production

databases:
  - name: shop-db
    databaseName: shop_acc_garena
    user: shop_user
