services:
  - type: web
    name: shop-ban-acc-garena
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: shop-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: ENCRYPTION_KEY
        generateValue: true

databases:
  - name: shop-db
    databaseName: shop_acc_garena
    user: shop_user
