services:
  - type: web
    name: gamevault
    env: python
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: cd GameVault && gunicorn --pythonpath . app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false